### ISSUE TITLE
Airgap Vault not generating secrets on Android-derived platforms

### ISSUE THREAD

**Issue by salazarp** [airgap-it/airgap-vault#102]
I cannot generate secrets upon starting AirGap Vault. After a second or two the icons for audio, video and movement grey out; and the percentage for doodling on the screen never goes up either.

This is a Huawei P9lite (~2017) with Android 7 / EMUI 5.

I have manually given permissions to the app for Audio and Video, but the behaviour persists. Perhaps linked to #100.

**NOTE**: This issue has been ack'ed in Telegram and apparently affects Android/EMUI, LineageOS, FireOS.

**Comment by AndreasGassmann** [comment]
Hi, sorry to hear you are having this issue. We do have issues with a few Android "forks", but this usually results in either not running at all, or refusing to run because it is falsely detected as rooted.

Does importing a secret work? If it does, would it be possible that you export your local error history and send it to us?

So the steps would be:
1. Start Vault and try to generate a secret (which will probably result in some unknown, internal error)
2. Go back, import a random mnemonic (NOT one that has funds on it!)
3. Go to the settings > "Danger Zone" > copy local error history. Then somehow send us what has been copied to your clipboard. If your device is fully airgapped, maybe you can paste it in a notes app and then take a few pictures/video of the screen. (We will make this easier in a future version).

Ideally, this would show us an error message that might point us to where the error might be.

**Comment by salazarp** [comment]
I'm afraid the clipboard is borked as well (within Vault).

I have done: 
- Import / Save your secret / Give label / Confirm  (-> clicking Confirm does nothing.)

Then go back to 
- Settings / Danger Zone / Copy Error History / I understand / Copy

Go to the notepad, and nothing gets pasted.

If I try using the clipboard icon while in "Import secret", nothing gets copied to the clipboard either.

Copy-pasting within a note, or in other apps works fine. Is there any other way I can debug? Thank you.

ps. just to confirm: this phone is not rooted and has been reset to factory defaults.

**Comment by salazarp** [comment]
Got it, the problem was webview. Following the [update webview article](https://support.airgap.it/guides/update-webview/) in the Help Center and upgrading Chrome did the trick. 

You can add Huawei P9 lite (VNS-L31) to the list of supported devices if you want. Running Android 7 + EMUI 5. Thanks!
