### ISSUE TITLE
GPG key handling

### ISSUE THREAD

**Issue by RoGryza** [airgap-it/airgap-vault#14]
Is it possible to manage GPG keys using vault? I don't mind if I have to hack something together, I can also submit a PR if it's a desired feature

**Comment by AndreasGassmann** [comment]
Hey, sorry for the late reply.

It's not possible to manage GPG keys in the Vault at the moment. It's definitely an interesting idea though.

What kind of features / mechanisms did you have in mind?

It would be nice if you would work on this in a PR, but I can't give you any promises that it will be merged to the main repo at this time. This seems like a bigger change and we would have to think about all the implications (also related to usability because we want to keep the app as simple as possible so it can also be used by non-technical people).

As a first step you could come up with a list of features that you would like to have, then we can see how that fits into the current design of the Vault.

**Comment by AndreasGassmann** [comment]
@RoGryza I've been thinking more and more about this over the last few weeks. Do you have some time and would be interested in working on this?

**Comment by RoGryza** [comment]
@AndreasGassmann sorry for the delay. I'm no longer working on the project I'd use this for, but I'll contact the team and see if they're still interested

**Comment by zsoltsandor** [comment]
I see that this has been mentioned, so I'm adding my own take to it: use OpenKeychain as the source of secret generation. That way no mnemonics, private keys, json files, or anything ever have to be exported anywhere, just connect directly to OpenKeychain. For an even better security scenario, you could generate the OpenPGP key on a hw (eg NitroKey), and then generate the vault secret from OpenKeychain. 

This option would only work on Android though, afaik.

**Comment by debeldami** [comment]
The activity on this issue has been inactive for the past two years. I'll be closing it now. If there's a need to revisit this matter, please don't hesitate to reopen the issue. Thank you.
