### ISSUE TITLE
Manually Add Token Contract Address?

### ISSUE THREAD

**Issue by vindicatorr** [airgap-it/airgap-vault#141]
https://support.storj.io/hc/en-us/articles/360026611052-How-can-I-manually-configure-the-STORJ-token-to-become-visible-in-my-wallet-
I am aware of manually setting the "derivative path", but was wondering about manually adding ERC-20 tokens?
I just became aware of WalletConnect.

I haven't dabbled yet, but am merely exploring/learning.

**Comment by AndreasGassmann** [comment]
Hi, thanks for opening the issue.

To access ERC20 tokens, the preferred solution is to use AirGap Vault together with MetaMask (see guide: https://support.airgap.it/guides/metamask)

You an also use a dApp like https://www.myetherwallet.com/ and connect to AirGap Wallet via WalletConnect.

**Comment by AndreasGassmann** [comment]
The reason for this is mainly the effort it takes to add the feature and maintenance. We already have support for the most common tokens and our integrations (MetaMask and WalletConnect) allow users to manage the rest of the tokens. There are other features that will bring more value because they add things that are not yet possible, for example. So we try to focus our time on those.

But if anyone would be willing to open a PR for this feature, we'd be happy to merge it.
