### ISSUE TITLE
import private key

### ISSUE THREAD

**Issue by jpph** [airgap-it/airgap-vault#16]
Would be nice to be able to import private key (with optional bip38 password), so we could use airgap vault to securely spend paper wallet.
Also would be nice to support segwit (3xxx keys) and bech32 (bcxxx keys)

**Comment by AndreasGassmann** [comment]
Hi, sorry for the late reply.

We generally advise users to generate a new secret when starting to use AirGap because of the risk that the "old" key was leaked during generation or storage. This is why we don't support many different ways of importing existing mnemonics/private keys generated in other wallets.

However, I see the use case here and it would be a nice feature to have. We'll discuss this internally and let you know what we decide. We currently have a lot of other tasks open / planned, so we'll probably not get to it for a while though.

But thanks for the suggestion!
