### ISSUE TITLE
sync QR code not showing 

### ISSUE THREAD

**Issue by katat** [airgap-it/airgap-vault#160]
When the vault is not HD type, the QR code for metamask from wallet sync isn't shown. 

Maybe this is a bug?

**Comment by AndreasGassmann** [comment]
Hi, thanks for creating this issue.

As far as I know, MetaMask cannot import non-HD wallets via QR code. Unless I'm mistaken and it is indeed possible, the bug here would be that the "MetaMask" button shouldn't be shown for non-HD wallets at all.

We'll remove the "MetaMask" button in the next release, thanks for the report.
