### ISSUE TITLE
New professional third party audit

### ISSUE THREAD

**Issue by alfredonodo** [airgap-it/airgap-vault#167]
Hi,
this project is very interesting because it is open source, with reproducible and cross-platform builds. Please update the audit as it is very important to have it for trust in the project.
Thank you

**Comment by AndreasGassmann** [comment]
Hi, thanks for reaching out. We'd love to do additional external audits. The problem is that professional audits are very expensive. Currently, we're focussing our efforts on some bigger internal changes to make our apps more modular and improve the security. It would be great to have those changes reviewed once they are done. So if you have any ideas on how we can make that happen, we'd be happy to hear it!

**Comment by alfredonodo** [comment]
Hi,
one idea could be crowdfunding/donations from wallet users and cryptocurrency enthusiasts.
The audit together with the support of the [top 50 cryptocurrencies](https://cryptpad.fr/sheet/#/2/sheet/view/gQktVo8RG4tweqM9WY1pRGDh+q9-t3RdmGESenUDjmc/) would make airgap the best universal wallet.
