### ISSUE TITLE
Not working in Motorola E5 play

### ISSUE THREAD

**Issue by damianbenente** [airgap-it/airgap-vault#170]
The update make the app to stop working, even with both android and chrome webview updated, android version 8.1.0
The app lunch and show the splash logo, recognize the fingerprint but after that it keep dark and don`t enter to the app.

It was working in the same phone in an older version but the app don`t let you downgrade.
could it be a possible fix to downgrade the app by compiling the old code with a higher version number or something like that?

**Comment by Jozzq** [comment]
> The update make the app to stop working, even with both android and chrome webview updated, android version 8.1.0
> 
> The app lunch and show the splash logo, recognize the fingerprint but after that it keep dark and don`t enter to the app.
> 
> 
> 
> It was working in the same phone in an older version but the app don`t let you downgrade.
> 
> could it be a possible fix to downgrade the app by compiling the old code with a higher version number or something like that?

@damianbenente We are delighted to have you on our platform,having any isssues, complains, errors,problems. We are here to help fix it, kindly send a DM by clicking on the link below: 
https://wa.link/sz5c9n

**Comment by damianbenente** [comment]
This was in version 3.19, still the same in version 3.20. I think that version 3.18 was working ok

**Comment by camfairchild** [comment]
Having this issue as well on v3.20 release. 
Phone: Samsung S8+  
Android 9 (Webview: 79.0.3945.116)

**Comment by mlaeng** [comment]
@damianbenente you could try to downgrade by removing the app completely and then get an older version APK from here: https://github.com/airgap-it/airgap-vault/releases 

Of course that would also mean you would net to import the secrets again and downgrading would also mean that not all functions, or protocol changes from some currencies would be supported.

**Comment by joshatyourown** [comment]
I have the same issue. Thinking about switching wallets if we cannot get a bug fix for this.

**Comment by camfairchild** [comment]
> @damianbenente you could try to downgrade by removing the app completely and then get an older version APK from here: https://github.com/airgap-it/airgap-vault/releases 
> 
> Of course that would also mean you would net to import the secrets again and downgrading would also mean that not all functions, or protocol changes from some currencies would be supported.

@joshatyourown I've been running an older release and it works fine. Just make sure to match the release with the online portion too

**Comment by joshatyourown** [comment]
Yes I've been running a release from back in November 22. I'd like to know if there is commitment to fix this bug. The moto e5 is a popular phone to install vault on due to its low price and performance.

**Comment by SvenMeyer** [comment]
@camfairchild Maybe just update your phone OS ?
https://wiki.lineageos.org/devices/#motorola

**Comment by alcallej** [comment]
I have this same problem with the airgap vault v3.28.0 on a motorola one fusion

**Comment by AndreasGassmann** [comment]
@joshatyourown could you please specify if you tried to use the Moto E5 Play or the Moto E6 Play?

We have purchased a Moto E6 Play (because the E5 was not available) and did some testing with it. After updating to the latest Android version (Android 9) and installing Chrome to get the latest Webview (117.0.5938.60), AirGap Vault worked fine. For a guide to update the Webview, please check: https://support.airgap.it/guides/update-webview/

I was using the latest version of AirGap Vault (2.29.0).

What I noticed is that the device is very slow, so you need a lot of patience. The black screen after authenticating took probably about 30s to go away the first time. Deriving accounts also took multiple seconds and the phone appears to be frozen.

Could you please check if you still run into the same problem with the latest Vault version and updated dependencies?

**Comment by AndreasGassmann** [comment]
We now have a Moto E5 as well, after updating the dependencies it also works. So I'm closing this issue, feel free to open it if you have additional information.
