### ISSUE TITLE
Newer deb for airgap-distro?

### ISSUE THREAD

**Issue by jonathancross** [airgap-it/airgap-vault#18]
Hi, I just found this project and [airgap-distro](https://github.com/airgap-it/airgap-distro) and started to poke around.

I noticed that airgap-distro hasn't been updated since 2018 and that the vault version being included is extremely old `v1.3.1`:
https://github.com/airgap-it/airgap-distro/blob/master/distro_build_script.sh#L22

But  [v1.3.1](https://github.com/airgap-it/airgap-vault/releases/tag/v1.3.1) seems to be the latest deb available here.  Is there a reason that new deb files are not being created?

Thanks.

**Comment by AndreasGassmann** [comment]
Hi, thanks for reaching out.

The reason for the deb files not being updated is simply because there wasn't a lot of demand for it, most people prefer to go with the mobile apps because it's more convenient.

We'll look into adding the deb build to our CI as well, which would then allow us to push out regular updates just like for the apps. But I can't give you a timeline for that.

**Comment by toonsevrin** [comment]
I'd like this as well.

**Comment by dekiesel** [comment]
+1

**Comment by jonathancross** [comment]
I just took a look and it seems this was not actually completed, but just closed.  Seems the devs believe it is not worth maintaining / updating https://github.com/airgap-it/airgap-distro
