### ISSUE TITLE
crash when creating new seed

### ISSUE THREAD

**Issue by SvenMeyer** [airgap-it/airgap-vault#185]
I experience reproducible crash with a fresh install of the latest version when trying to generate a new seed.

Permissions should be ok (see screenshot)

- device : Google Pixel 3
- OS : GrapheneOS (Android 12 / blueline-factory-2022072000)

![AirGap-Vault- permissions](https://user-images.githubusercontent.com/25609/220546578-65d8cee6-1590-42c2-98cd-eae71c755128.jpg)

![AirGap-Vault- seed-generation-crash](https://user-images.githubusercontent.com/25609/220545948-de984379-d8a3-4cb4-b6e3-c115245ec1ce.jpg)

**Comment by SvenMeyer** [comment]
I just tried the latest version v3.23.1 , airgap-vault-49677.apk ... still crashing :-(

**Comment by mlaeng** [comment]
Noted. But it might take a while until we have time to investigate. What you could try is to remove camera permissions for seed generation. The entropy should then be collected from audio, scribbles and gyro only. After generating the seed, you will have to tun on camera access again in order to be able to scan QR codes. If you want to try this, pls report back. Thank you!

**Comment by SvenMeyer** [comment]
I removed the right for video in system settings and also chose later in the pop-up that Airgap-Vault is not allowed to access the camera .. that worked !
