### ISSUE TITLE
Improve seed recover functionality

### ISSUE THREAD

**Issue by lukeisontheroad** [airgap-it/airgap-vault#3]
- [ ] Ignore case
- [ ] mnemonic auto completion

**Comment by prodnet** [comment]
Hi, Dev team

Impossible to recover mnemonic seed by import or social recovery.

Unfortunately, the problem persists, when do you think  you can implement correctly the options  "import"  and "social recovery" because are not functional and this application can not be used under these conditions !

Future suggested options::

* auto completion of mnemonic seed after N chars
* plausible deniability
* lock application with a password
* auto-delete after N wrong passwords
* social recovery external standalone file (html and javascript.)
( Ex: https://github.com/iancoleman/iancoleman.io/blob/master/shamir39/index.html)

I hope these suggestions will motivate you to greatly improve this application, which could become a competitor of BRD Wallet.

**Comment by AndreasGassmann** [comment]
Hey, I just saw that we never actually wrote you back. This was a long time ago, but maybe someone else who has the same problem in the future can profit from this response.

I can say with confidence that the secret import and recovery have **always** worked, but in the beginning we had some UI quirks that could result in odd behaviour. If you were not able to import your mnemonic or social recovery, it most likely means you had a typo in one of the words (https://github.com/airgap-it/airgap-vault/issues/2).

There is still room for improvement, for example could we display which of the words are unknown (not in the wordlist) or if only the order is wrong. We already have an internal issue where we are tracking this request and I'll update this ticket once we release something.
