### ISSUE TITLE
Future suggested options

### ISSUE THREAD

**Issue by prodnet** [airgap-it/airgap-vault#6]
Future suggested options::

auto completion of mnemonic seed after N chars
plausible deniability
lock application with a password
auto-delete after N wrong passwords
social recovery external standalone file (html and javascript.)
( Ex: https://github.com/iancoleman/iancoleman.io/blob/master/shamir39/index.html)
I hope these suggestions will motivate you to greatly improve this application, which could become a competitor of BRD Wallet.

**Comment by cryptoida** [comment]
Yes, the application is interesting but actually lacks elementary options, such as:
- Automatic lock when closing the application or after a period of inactivity of a few minutes.
- Detection and automatic listing of ETH tokens (ERC20).
- Plausible deniability by passphrase  the ultimate protection for accounts (as Tezor and Ledger hardware wallets)
Let's hope these features will be implemented soon. :)

**Comment by pascuin** [comment]
Thank you very much to both to you for your feedback.

> auto completion of mnemonic seed after N chars

This is something we have on our feature list and will be implemented as soon as possible.

> Plausible deniability by passphrase  the ultimate protection for accounts (as Tezor and Ledger hardware wallets)

Good to hear that plausible deniability is a feature that comes requested, we've added this to our feature request list, see also #5 for an answer.

> Automatic lock when closing the application or after a period of inactivity of a few minutes.

What would be the use case for this? We currently ask for authentication when accessing the secure storage ex. signing a transaction - Other than that the app can be used without authentication, what would be the rational to do this globally for the app?

> auto-delete after N wrong passwords

As we don't allow currently to access the secret/recovery phrase after the initial validation, I don't see a use case for this. What would be the idea behind this?

> social recovery external standalone file (html and javascript.)

A social recovery option outside the application is somewhat tricky as it deals with splits of a secret, depends a bit on how it can be accessed, a hosted version does not make sense in my opinion.

> Detection and automatic listing of ETH tokens (ERC20).

Part of the development currently is funded through integrations, this also applies to ERC20 tokens. We'll gradually add more tokens in the near future but currently there is no plan to support every token out of the box. Would be great to get some feedback from you what your thoughts are @cryptoida

**Comment by cryptoida** [comment]
> Automatic lock when closing the application or after a period of inactivity of a few minutes.

For better visual confidentiality, if more people have access to the device. (wife, children, friends).

> Detection and automatic listing of ETH tokens (ERC20).

Users and investors are not just happy with a simple wallet in which they do not have the opportunity to associate their tokens with their ETH address.

I understand that the initial motivation to develop this wallet was a funding, but I think that as a user, the lack of automatic listing of ETH ERC20 tokens, it is one of the biggest obstacles in mass adoption of this wallet.

In conclusion, it is a waste for both those who have funded the project and future prospective clients.

> AirGap Wallet Chrome Extension 

I've tested this crome extension, but it interacts hard with MetaMask.
Instead, it works well with Web3 dapps.
There may be a possibility to implement a much secure solution such as WalletConnect
https://walletconnect.org/

**Comment by dcale** [comment]
@cryptoida your feedback is very good. However to clarify: the last of our motivation with this open source project is funding, would it be funding the project would've been setup in a different way. 

The main motivation is to provide to the community the most secure and accessible wallet/system to manage their crypto assets and ultimately adding value to the crypto community. This motivation is what drives this project since day 1. The team members behind AirGap use their years of experience in developing mobile security solutions for large financial institutions to achieve that vision.

Mass adoption is achieved by:
1. getting like-minded people (people that believe an open source, secure and accessible wallet/system is important for the community) to support the project in their social circles and providing valuable feedback just like you did in order to move the project forward.
2. find a sustainable setup for this open source project to succeed long term

It's no secret that security audit reviews cost a lot of money and "blindly on-boarding every possible ERC20" will have a negative impact on security. For that reason we decided that instead we provide users still a way to transfer any ERC20 or perform any smart contract call but by using the chrome extension. If you believe that blindly providing support of every ERC20 token is more important than security I'm afraid this project is not what you are looking for.

**Comment by pascuin** [comment]
> I've tested this crome extension, but it interacts hard with MetaMask.
Instead, it works well with Web3 dapps.
There may be a possibility to implement a much secure solution such as WalletConnect
https://walletconnect.org/

Can you clarify this a bit more? The approach for the AirGap Wallet Chrome Extension is that it works with Web3 dapps and it's injected the same as MetaMask, this means that it should be compatible with every dapp that is MetaMask compatible.

The Chrome Extension has the same functionalities as the AirGap Wallet on a mobile device, it is the communication layer between the offline device and the protocol.

Interaction with an offline device does not work with WalletConnect as it needs a connection between the two devices.

**Comment by cryptoida** [comment]
I think you misunderstood me, it is obvious that security is primordial.
As the ERC20 tokens are smart contracts associated with an ETH address, I did not think their automatic listing, directly impacts the security of the wallet.

**Comment by cryptoida** [comment]
> AirGap Wallet Chrome 

I can not connect with AirGap Wallet Chrome Extension at airswap.io

**Comment by pascuin** [comment]
Thanks for the feedback, we still need to test various compatibilities, we add airswap.io to the list.

**Comment by cryptoida** [comment]
*I'm curious to find out if AirGap Vault might be vulnerable to the attacks and vulnerabilities found in Trezor and Ledger  hardware wallets?

Video source:
https://www.youtube.com/watch?v=c0iEg42aAhk

*What would be the ideal smartphone hardware configuration?
*What level of security does AirGap Vault offer, compared to Trezor and Ledger hardware wallets?

**Comment by dcale** [comment]
the video shows various attacks, I went through the first two, since the last one is not really explained:
1. the malicious firmware upgrade attack: is mitigated on Android and iOS by using the according cryptographic system provided by the OS, i.e. on Android you can never upgrade the vault if the package was signed with a new private key, updates will only be possible with the same private key used during the first install. Furthermore the actual signing of the distribution package happens in an airgapped setup for Android. 
2. side channel attacks: airgap has an advantage here because there is (almost) no physical connection to the outside if you use an offline device on battery. The only attack we could think of is by measuring the magnetic field the cpu generates while signing a transaction, however these attacks tend to get very esoteric and we might be missing some.

In general one can say: if you really follow an airgapped approach with an offline device (preferrably Android) then the security level will be equal or higher than anything physically connected (we count nfc, ble as a physical connection). If you use a same device approach, your secret will be on a "hot" device and hence the level of security will be equal or lower to what a physically connected device can offer. You still can profit from sandboxes and the OS security (i.e. disabled network permissions on Android) but side channel attacks or other forms of injection/eaves dropping will be easier than when having a physical air gap.

**Comment by sirius2013** [comment]
@pascuin  How are you?
I saw this project is ionic3, I can help to update ionic4.
could we discuss as soon as possible?

**Comment by NickRiddle0606** [comment]
Hello
I want to dedicate to migrate or review ionic 4 if you need.

**Comment by NickRiddle0606** [comment]
Hello there?
How is it going?

**Comment by AndreasGassmann** [comment]
@NickRiddle0606 The ionic4 migration is already in progress, we don't need any help. Thanks

**Comment by NickRiddle0606** [comment]
okay, good. let me know if have problem or that is done.
eager to see that.

**Comment by NickRiddle0606** [comment]
@AndreasGassmann

**Comment by NickRiddle0606** [comment]
Hello guys. @pascuin  @airgap-gitlab 
any update for this?
I am eager to see ionic4 version soon.

Cheers

**Comment by debeldami** [comment]
We now support majority of the features suggested in the initial comment of this isssue. 

The [auto completion](https://support.airgap.it/airgap-vault/secure-keyboard) feature comes with our introduction of the secure keyboard in AirGap.

> auto completion of mnemonic seed

You can visit this [guide](https://support.airgap.it/guides/bip39/) to learn how to use plausible deniability in AirGap

> plausible deniability

We support encryption password which allows you to lock the Vault with a password different from the inbuilt means of authentication.

> lock application with a password

Not yet supported

> auto-delete after N wrong passwords

You can visit this [page](https://airgap-it.github.io/airgap-standalone-social-recovery/) for the social recovery external standalone file

> social recovery external standalone file 

As a result, I'll go ahead and close this issue.
