### ISSUE TITLE
[Request] More supported blockchains/tokens

### ISSUE THREAD

**Issue by Ahmed-Ali** [airgap-it/airgap-vault#80]
Big fan here! Thank you for all the amazing work.

As I am starting to use Airgap more and more, I find my self missing some fast growing projects. And here are the ones on top of my mind I wish to see supported:

- Cardano
- Polygon
- Solana (SOL)
- Uniswap
- Sushiswap
- Algorand
- Stellar Lumans

Also seem like not all ERC20 tokens are supported; the one I am wishing for is POLY

**Comment by AndreasGassmann** [comment]
As for ERC20 tokens, you can actually use MyEtherWallet and connect AirGap Wallet with WalletConnect, then you can add custom ERC20 tokens to MEW and work with it from there. Not ideal, but it works for now.

Regarding other chains, the issue is as always available resources. Adding a new protocol takes a long time if done right. It involves understanding the protocol, implementing the required functionality in our library, setting up nodes and then maintaining all of this. Especially the maintenance is often underestimated, specifically for new projects that often have breaking changes. There were a few times where we had to do emergency releases for DOT/KSM because they pushed a breaking change to their nodes.

If we add a chain, it is usually with the help / funding of the chain itself. This allows us to dedicate the time and maintain it. As AirGap gets more popular, we hope that interest of those projects in an integration increases as well.

We are also playing around with the idea of "community maintained" protocols. This would allow us (or community members) to add support for new chains quickly, without requiring our "stamp of approval" or our commitment to provide support and maintenance. But at this point it's just an idea without an actual plan, we're happy for feedback.

**Comment by debianlima** [comment]
Experimental project: **AirGap Vault Kaizou 1.1.2 — Solana wallet / Solflare support**

This issue mentions Solana support, so this may be relevant as an experimental reference. The project explores **Solana in an air-gapped flow**, using offline QR/BC-UR signing and interoperability with Solflare/Keystone-style requests.

It is **not an official release of AirGap, Solflare, Keystone, PancakeSwap, or Solana**. There has been **no independent security audit**. Please review the code, commits, artifacts, and hashes yourself before any use. Use is entirely at your own risk, and the test results should not be treated as a guarantee of safety for real funds.

Experimental release: https://github.com/debianlima/airgap-vault-kaizou/releases/tag/airgap-vault-kaizou-1.1.2

APK SHA-256: `6885cc59cc9f0050bb0e2614ac4a0a4c165aa0011f086e3e8b68881dd3742a45`

---
**Automatic translation (PT-BR):**

Projeto experimental: **AirGap Vault Kaizou 1.1.2 — suporte Solana wallet / Solflare**. Esta issue menciona suporte a Solana, então o projeto pode servir como referência experimental. Ele estuda Solana em fluxo air-gapped com assinatura offline por QR/BC-UR e interoperabilidade com solicitações no formato Solflare/Keystone. Não é uma versão oficial, não houve auditoria de segurança independente, e o uso é inteiramente por conta e risco do usuário. Revise código, commits, artefatos e hashes antes de qualquer uso.
